---
version: 0.2
phases:
  install:
    commands:
      - apk update
      - apk add py-pip hugo
      - pip install awscli
  build:
    commands:
      - hugo
      - aws s3 sync ./public s3://${DEPLOYMENT_BUCKET}/ --acl=public-read
