baseurl = "https://www.mexico86.co.uk"
title = "Mexico86"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
uglyURLs = true

paginate = 20
canonifyurls = true

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    author = "Mexico86" # Author's name.
    info = "Technical Consulting" # Author's job title or info.
    description = "Mexico86: Technical Consulting" # Site description.
    keywords = "Mexico86,mxco86,technical consulting,technology,strategy,serverless,aws" # Site keywords.
    avatarurl = "/images/86.png" # Contain the path of the optional avatar in the static folder.

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

#    footercontent = "◆"
    footercontent = ""

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/mxco86.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1

    url = "https://github.com/mxco86"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/mxco86"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/matthew-ryall-7511ba1/"

# Menu links
# [[menu.main]]
#    name = "Blog"
#    weight = 2
#    url  = "/posts.html"
[[menu.main]]
    name = "Personnel"
    weight = 1
    url = "/personnel/matthew-ryall.html"
[[menu.main]]
   name = "Services"
   weight = 2
   url  = "/services.html"
