baseurl = "https://www.mexico86.co.uk"
title = ""
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
uglyURLs = true

paginate = 20
canonifyurls = true

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    author = "" # Author's name.
    info = "Technical Consulting" # Author's job title or info.
    description = "Mexico86: Handmade Technology" # Site description.
    keywords = "mexico86,mxco86,technology,strategy,serverless,aws" # Site keywords.
    avatarurl = "images/86.png" # Contain the path of the optional avatar in the static folder.

    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"

#    footercontent = "◆"
    footercontent = ""

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/mxco86.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1

    url = "https://github.com/mxco86"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/mxco86"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/matthew-ryall-7511ba1/"
[[params.social]]
    name = "Services"
    icon = "fas fa-concierge-bell fa-2x"
    weight = 4
    url = "/services.html"

# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/posts.html"
# [[menu.main]]
#     name = "About"
#     weight = 2
#     url = "/about.html"
